/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedCentralRouteRouteImport } from './routes/_authenticated/central/route'
import { Route as AuthenticatedCentralIndexRouteImport } from './routes/_authenticated/central/index'
import { Route as AuthenticatedCentralSlugRouteImport } from './routes/_authenticated/central/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCentralRouteRoute =
  AuthenticatedCentralRouteRouteImport.update({
    id: '/central',
    path: '/central',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentralIndexRoute =
  AuthenticatedCentralIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCentralRouteRoute,
  } as any)
const AuthenticatedCentralSlugRoute =
  AuthenticatedCentralSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCentralRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/central': typeof AuthenticatedCentralRouteRouteWithChildren
  '/central/$slug': typeof AuthenticatedCentralSlugRoute
  '/central/': typeof AuthenticatedCentralIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/central/$slug': typeof AuthenticatedCentralSlugRoute
  '/central': typeof AuthenticatedCentralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/central': typeof AuthenticatedCentralRouteRouteWithChildren
  '/_authenticated/central/$slug': typeof AuthenticatedCentralSlugRoute
  '/_authenticated/central/': typeof AuthenticatedCentralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/central' | '/central/$slug' | '/central/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/central/$slug' | '/central'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/central'
    | '/_authenticated/central/$slug'
    | '/_authenticated/central/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/central': {
      id: '/_authenticated/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof AuthenticatedCentralRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/central/': {
      id: '/_authenticated/central/'
      path: '/'
      fullPath: '/central/'
      preLoaderRoute: typeof AuthenticatedCentralIndexRouteImport
      parentRoute: typeof AuthenticatedCentralRouteRoute
    }
    '/_authenticated/central/$slug': {
      id: '/_authenticated/central/$slug'
      path: '/$slug'
      fullPath: '/central/$slug'
      preLoaderRoute: typeof AuthenticatedCentralSlugRouteImport
      parentRoute: typeof AuthenticatedCentralRouteRoute
    }
  }
}

interface AuthenticatedCentralRouteRouteChildren {
  AuthenticatedCentralSlugRoute: typeof AuthenticatedCentralSlugRoute
  AuthenticatedCentralIndexRoute: typeof AuthenticatedCentralIndexRoute
}

const AuthenticatedCentralRouteRouteChildren: AuthenticatedCentralRouteRouteChildren =
  {
    AuthenticatedCentralSlugRoute: AuthenticatedCentralSlugRoute,
    AuthenticatedCentralIndexRoute: AuthenticatedCentralIndexRoute,
  }

const AuthenticatedCentralRouteRouteWithChildren =
  AuthenticatedCentralRouteRoute._addFileChildren(
    AuthenticatedCentralRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCentralRouteRoute: typeof AuthenticatedCentralRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCentralRouteRoute: AuthenticatedCentralRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
